/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package video.player;

import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import uk.co.caprica.vlcj.player.base.MediaPlayer;
import uk.co.caprica.vlcj.player.base.MediaPlayerEventAdapter;

/**
 *
 * @author santi
 */
public class frameVideoPlayer extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameVideoPlayer.class.getName());

    private EmbeddedMediaPlayerComponent mediaPlayerComponent;

    private File[] playList;

    private Integer playPosition = null;

    private final DefaultListModel<VideoItem> modelo = new DefaultListModel<>();
    private JList<VideoItem> listaVideos;

    private boolean loopActivo = false;

    /**
     * Creates new form frameVideoPlayer
     */
    public frameVideoPlayer() {

        initComponents();

        configurarPanelVideo();

        configurarLista();

        configurarEventos();

        String userHome = System.getProperty("user.home");

        File videoFolder = new File(userHome, "Videos");

        if (!videoFolder.exists()) {

            videoFolder = new File(userHome, "Movies"); // Mac

        }

        if (!videoFolder.exists()) {

            videoFolder = new File(userHome, "Video"); // alternativa

        }

        System.out.println(videoFolder.getPath());

        loadPlayList(videoFolder.getAbsolutePath());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVideo = new javax.swing.JPanel();
        jPanelPrevs = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        botonRebobinar = new javax.swing.JButton();
        botonPlay = new javax.swing.JButton();
        botonUpload = new javax.swing.JButton();
        botonLoop = new javax.swing.JButton();
        botonStop = new javax.swing.JButton();
        botonSalto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelVideo.setBackground(new java.awt.Color(0, 0, 0));
        jPanelVideo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelVideo.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout jPanelVideoLayout = new javax.swing.GroupLayout(jPanelVideo);
        jPanelVideo.setLayout(jPanelVideoLayout);
        jPanelVideoLayout.setHorizontalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelVideoLayout.setVerticalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelPrevsLayout = new javax.swing.GroupLayout(jPanelPrevs);
        jPanelPrevs.setLayout(jPanelPrevsLayout);
        jPanelPrevsLayout.setHorizontalGroup(
            jPanelPrevsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanelPrevsLayout.setVerticalGroup(
            jPanelPrevsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        botonRebobinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/boton-de-rebobinado (1).png"))); // NOI18N
        botonRebobinar.addActionListener(this::botonRebobinarActionPerformed);

        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/boton-play.png"))); // NOI18N
        botonPlay.addActionListener(this::botonPlayActionPerformed);

        botonUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/upload.png"))); // NOI18N
        botonUpload.addActionListener(this::botonUploadActionPerformed);

        botonLoop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loop.png"))); // NOI18N
        botonLoop.addActionListener(this::botonLoopActionPerformed);

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/detener.png"))); // NOI18N
        botonStop.addActionListener(this::botonStopActionPerformed);

        botonSalto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/boton-de-salto.png"))); // NOI18N
        botonSalto.addActionListener(this::botonSaltoActionPerformed);

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRebobinar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLoop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLoop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRebobinar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPrevs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrevs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelVideo.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        reproducirSeleccionado();
    }//GEN-LAST:event_botonPlayActionPerformed

    private void botonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUploadActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Seleccionar video");

        fileChooser.setFileFilter(
                new FileNameExtensionFilter(
                        "Videos",
                        "mp4", "mkv", "avi", "mov"
                )
        );

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado != JFileChooser.APPROVE_OPTION) {

            return;

        }

        File archivo = fileChooser.getSelectedFile();

        if (archivo == null || !archivo.exists()) {

            JOptionPane.showMessageDialog(this, "Archivo no válido.");

            return;

        }

        ImageIcon miniatura = obtenerPortadaAleatoria();

        modelo.addElement(
                new VideoItem(
                        archivo,
                        miniatura
                )
        );

        playList = new File[modelo.size()];

        for (int i = 0; i < modelo.size(); i++) {

            playList[i] = modelo.get(i).getArchivo();

        }

        playPosition = modelo.size() - 1;

        listaVideos.setSelectedIndex(playPosition);

        listaVideos.ensureIndexIsVisible(playPosition);

        reproducirArchivo(archivo);
    }//GEN-LAST:event_botonUploadActionPerformed

    private void botonLoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoopActionPerformed
        loopActivo = !loopActivo;

        if (loopActivo) {

            JOptionPane.showMessageDialog(this, "Loop activado.");

        } else {

            JOptionPane.showMessageDialog(this, "Loop desactivado.");

        }
    }//GEN-LAST:event_botonLoopActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed

        mediaPlayerComponent
                .mediaPlayer()
                .controls()
                .stop();
    }//GEN-LAST:event_botonStopActionPerformed

    private void botonSaltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaltoActionPerformed
        if (playList == null || playList.length == 0) {

            JOptionPane.showMessageDialog(this, "No hay videos en la lista.");

            return;

        }

        if (playPosition == null) {

            playPosition = 0;

        } else {

            playPosition++;

        }

        if (playPosition >= playList.length) {

            playPosition = 0;

        }

        listaVideos.setSelectedIndex(playPosition);

        listaVideos.ensureIndexIsVisible(playPosition);

        reproducirArchivo(playList[playPosition]);
    }//GEN-LAST:event_botonSaltoActionPerformed

    private void botonRebobinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRebobinarActionPerformed

        if (playList == null || playList.length == 0) {

            JOptionPane.showMessageDialog(this, "No hay videos en la lista.");

            return;

        }

        if (playPosition == null) {

            playPosition = 0;

        } else {

            playPosition--;

        }

        if (playPosition < 0) {

            playPosition = playList.length - 1;

        }

        listaVideos.setSelectedIndex(playPosition);

        listaVideos.ensureIndexIsVisible(playPosition);

        reproducirArchivo(playList[playPosition]);
    }//GEN-LAST:event_botonRebobinarActionPerformed

    private static void configurarRutaVlc() {

        String os = System.getProperty("os.name").toLowerCase();
        String vlcPath = null;

        if (os.contains("win")) {

            File vlc64 = new File("C:\\Program Files\\VideoLAN\\VLC");
            File vlc32 = new File("C:\\Program Files (x86)\\VideoLAN\\VLC");

            if (vlc64.exists()) {
                vlcPath = vlc64.getAbsolutePath();
            } else if (vlc32.exists()) {
                vlcPath = vlc32.getAbsolutePath();
            }

        } else if (os.contains("mac")) {

            File macVlc = new File("/Applications/VLC.app/Contents/MacOS/lib");

            if (macVlc.exists()) {
                vlcPath = macVlc.getAbsolutePath();
            }

        }

        if (vlcPath != null) {
            System.setProperty("jna.library.path", vlcPath);
            System.out.println("VLC path configurado: " + vlcPath);
        } else {
            System.err.println("No se encontró VLC instalado.");
        }
    }

    public void reproducirArchivo(File archivo) {

        if (archivo == null || !archivo.exists()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo no válido."
            );

            return;
        }

        try {

            mediaPlayerComponent
                    .mediaPlayer()
                    .controls()
                    .stop();

            boolean reproduciendo
                    = mediaPlayerComponent
                            .mediaPlayer()
                            .media()
                            .play(archivo.getAbsolutePath());

            if (!reproduciendo) {

                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo reproducir el archivo."
                );

                return;
            }

            System.out.println(
                    "Reproduciendo: " + archivo.getName()
            );

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al reproducir."
            );

            ex.printStackTrace();

        }

    }

    public void loadPlayList(String path) {

        File folder = new File(path);

        if (!folder.exists() || !folder.isDirectory()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ruta inválida"
            );

            return;
        }

        File[] listaArchivos = folder.listFiles();

        if (listaArchivos == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo leer la carpeta"
            );

            return;
        }

        modelo.clear();

        java.util.List<File> listaVideos
                = new java.util.ArrayList<>();

        for (File archivo : listaArchivos) {

            if (!archivo.isFile()) {
                continue;
            }

            String nombre
                    = archivo.getName().toLowerCase();

            if (!nombre.endsWith(".mp4")
                    && !nombre.endsWith(".mkv")
                    && !nombre.endsWith(".avi")) {

                continue;
            }

            listaVideos.add(archivo);

            ImageIcon miniatura = obtenerPortadaAleatoria();

            modelo.addElement(
                    new VideoItem(
                            archivo,
                            miniatura
                    )
            );

        }

        playList = listaVideos.toArray(File[]::new);

    }

    private void configurarPanelVideo() {

        jPanelVideo.removeAll();

        jPanelVideo.setLayout(new BorderLayout());

        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();

        jPanelVideo.add(mediaPlayerComponent, BorderLayout.CENTER);

        jPanelVideo.revalidate();

        jPanelVideo.repaint();

    }

    private void configurarLista() {

        listaVideos = new JList<>(modelo);
        listaVideos.setFixedCellHeight(100);

        listaVideos.setFixedCellWidth(250);

        listaVideos.setCellRenderer(
                new VideoRenderer()
        );

        jPanelPrevs.setLayout(new BorderLayout());

        jPanelPrevs.add(
                new JScrollPane(listaVideos),
                BorderLayout.CENTER
        );

    }

    private void configurarEventos() {

        listaVideos.addMouseListener(
                new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {

                if (e.getClickCount() != 2) {
                    return;
                }

                VideoItem item = listaVideos.getSelectedValue();

                if (item == null) {

                    return;

                }

                playPosition = listaVideos.getSelectedIndex();

                reproducirArchivo(
                        item.getArchivo()
                );

            }

        });

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {

                mediaPlayerComponent.release();

            }

        });

        mediaPlayerComponent
                .mediaPlayer()
                .events()
                .addMediaPlayerEventListener(
                        new MediaPlayerEventAdapter() {

                    @Override

                    public void finished(MediaPlayer mediaPlayer) {

                        SwingUtilities.invokeLater(() -> {

                            if (loopActivo) {

                                reproducirSeleccionado();

                            } else {

                                botonSaltoActionPerformed(null);

                            }

                        });

                    }

                });

    }

    private void reproducirSeleccionado() {

        VideoItem item = listaVideos.getSelectedValue();

        if (item == null) {

            if (modelo.isEmpty()) {

                JOptionPane.showMessageDialog(this, "No hay videos en la lista.");

                return;

            }

            listaVideos.setSelectedIndex(0);

            item = listaVideos.getSelectedValue();

        }

        playPosition = listaVideos.getSelectedIndex();

        reproducirArchivo(item.getArchivo());

    }

    private ImageIcon obtenerPortadaAleatoria() {

        int numero = 1 + (int) (Math.random() * 5);

        String ruta = "/assets/portada_" + numero + ".png";

        return new ImageIcon(
                getClass().getResource(ruta)
        );

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        configurarRutaVlc();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            frameVideoPlayer frame = new frameVideoPlayer();

            frame.setSize(1100, 650);

            frame.setLocationRelativeTo(null);

            frame.setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLoop;
    private javax.swing.JButton botonPlay;
    private javax.swing.JButton botonRebobinar;
    private javax.swing.JButton botonSalto;
    private javax.swing.JButton botonStop;
    private javax.swing.JButton botonUpload;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelPrevs;
    private javax.swing.JPanel jPanelVideo;
    // End of variables declaration//GEN-END:variables
}
